services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_PASSWORD=secret123%$1'
    ports:
      - 4200:5432

    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - pgdata:/var/lib/postgresql/data



volumes:
  pgdata: